version: "3"
services:
  bitfoil-nginx:
    container_name: bitfoil-nginx
    environment:
      - NGINX_USER=myuser
      - NGINX_PASSWORD=mypassword
    image: rsdevigo/bitfoil-nginx:latest
    volumes:
      - ./games:/games
    ports:
      - "8065:80"
  bitfoil-indexer:
    container_name: bitfoil-shop
    image: rsdevigo/bitfoil-indexer:latest
    environment:
      - SHOP_PATH=/games
      - SHOP_MOTD=Welcome to Bitfoil, the byte-sized shop!
    volumes:
      - ./games:/games
  bitfoil-torrent:
    container_name: bitfoil-torrent
    image: rsdevigo/bitfoil-torrent:latest
    environment:
      - TORRENT_PATH=/torrents
      - TORRENT_JSON_FILE=torrents.json
      - MAX_DOWNLOAD=2
      - GAMES_PATH=/games
    volumes:
      - ./games:/games
      - ./torrents:/torrents
